USE [master]
GO

/****** Object:  Database [LegoRobot]    Script Date: 04/24/2012 15:09:57 ******/
CREATE DATABASE [LegoRobot] ON  PRIMARY 
( NAME = N'LegoRobot', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LegoRobot.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LegoRobot_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LegoRobot_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LegoRobot] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LegoRobot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LegoRobot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LegoRobot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LegoRobot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LegoRobot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LegoRobot] SET ARITHABORT OFF 
GO

ALTER DATABASE [LegoRobot] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LegoRobot] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LegoRobot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LegoRobot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LegoRobot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LegoRobot] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LegoRobot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LegoRobot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LegoRobot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LegoRobot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LegoRobot] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LegoRobot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LegoRobot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LegoRobot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LegoRobot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LegoRobot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LegoRobot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LegoRobot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LegoRobot] SET  READ_WRITE 
GO

ALTER DATABASE [LegoRobot] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LegoRobot] SET  MULTI_USER 
GO

ALTER DATABASE [LegoRobot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LegoRobot] SET DB_CHAINING OFF 
GO

